version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RACK_ENV: development
    restart: on-failure
    stdin_open: true
    tty: true

  database:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
